# Generated by Django 4.2.2 on 2023-06-26 17:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('units', models.IntegerField()),
                ('volume', models.IntegerField()),
                ('content', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(0)])),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('link', models.CharField()),
                ('type', models.CharField()),
            ],
        ),
    ]
