# Generated by Django 4.2.2 on 2023-06-27 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinksData', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='alc_per_dol',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drink',
            name='talc',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drink',
            name='tvolume',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
