# Generated by Django 4.2.2 on 2023-06-27 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinksData', '0002_drink_alc_per_dol_drink_talc_drink_tvolume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='alc_per_dol',
            field=models.DecimalField(decimal_places=4, max_digits=7),
        ),
        migrations.AlterField(
            model_name='drink',
            name='talc',
            field=models.DecimalField(decimal_places=4, max_digits=8),
        ),
    ]
