# Generated by Django 4.2.2 on 2023-06-27 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinksData', '0003_alter_drink_alc_per_dol_alter_drink_talc'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
