# Generated by Django 4.2.2 on 2023-06-27 17:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinksData', '0005_drink_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='content',
            field=models.DecimalField(decimal_places=4, max_digits=7, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(0)]),
        ),
    ]
